### PR TITLE
Speed up adapt_hourly_year_profile_to_day_averaged_with_hourly_peak_day by a factor of 6.

### PR DESCRIPTION
**Pull request by lfse-slafleur**
Hope I am not overstepping. Took some time today to get the profiler tool up and running and I noticed there was a single operation that took some time but I didn't understand why. So here is a preview of a proposed performance fix!

`adapt_hourly_year_profile_to_day_averaged_with_hourly_peak_day` took 12.44 seconds for 36 heat demand profiles using the `graph_HDemands_incl_demand_4.esdl` ESDL.

The cause is due to lineair complexity of `set_data_with_averages_and_peak_day`. It is called once for each heat demand profile. However, this function performed significant operations on the pandas.Timestamp datastructure. Operations on this structure are expensive and it seems they aren't necessary for the functionality of the operation to remain the same.

Proposed fix: Use seconds since start (a float) instead of `pandas.Timestamp` for `set_data_with_averages_and_peak_day`.
This brings down the operation from 12.44 seconds to 2.13 seconds on the above ESDL.

### CODE REVIEW

**Comment by KobusVanRooyen** [comment]
Thanks @lfse-slafleur. I will have a look

**Comment by KobusVanRooyen** [comment]
@lfse-slafleur can you please update the CHANGELOG so that this can be merged

**Review by KobusVanRooyen — COMMENTED** [review]
Update CHANGELOG please

**Comment by lfse-slafleur** [comment]
@KobusVanRooyen Changelog Added

**Review by KobusVanRooyen — APPROVED** [review]

**Pull request merged**
